<<<<<<< Updated upstream
=======
version: '3.3'
services:
  myapp1:
    image: appimage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 11000:11000
    volumes:
      - .:/usr/src/app
    container_name: myapp1
    networks:
      - appnet
  myapp2:
    image: appimage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .:/usr/src/app
    container_name: myapp2
    networks:
      - appnet
  myapp3:
    image: appimage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .:/usr/src/app
    container_name: myapp3
    networks:
      - appnet
  myapp4:
    image: appimage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - .:/usr/src/app
    container_name: myapp4
    networks:
      - appnet

networks:
  appnet:





>>>>>>> Stashed changes
