package csd.wallet.Enums;

public enum RequestType {

    TEST_1,
    TEST_2,
    TEST_3,
    TEST_4,

    WALLET_CREATE,
    WALLET_DELETE,
    WALLET_AMOUNT,
    WALLET_INFO,

    TRANSFERS_ADD,
    TRANSFERS_REMOVE,
    TRANSFERS_TRANSFER,
    TRANSFERS_GLOBALTRANSFERS,
    TRANSFERS_WALLETTRANSFERS,
    TRANSFERS_DATETRANSFERS,

    SMART_CONTRACT_EXECUTE,

    ACCOUNT_CREATE, LOGIN;

}
